name: Build & Sync Packages

on:
  push:
    branches:
      - main
    paths:
      - 'packages.json'
      - '.github/workflows/build-packages.yml'
      - '.github/workflows/scripts/**'

  schedule:
    - cron: '0 0 * * 1'

  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    
    permissions:
      packages: read
      contents: write

    container: 
      image: ghcr.io/${{ github.repository_owner }}/archlinux-builder:latest

    steps:

      - name: Update system and install GH cli
        run: sudo pacman -Syu --noconfirm github-cli
  
      - name: Setup git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      
      - name: Checkout arch-repo
        uses: actions/checkout@v4
        with:
          path: arch-repo
          fetch-depth: 0

      - name: Load config
        run: |
          cp arch-repo/packages.json .
          mkdir -p out
          gh release download aarch64 --repo ${{ github.repository }} --dir ./out --pattern build-state.json --pattern ${{ github.repository_owner }}.db* --pattern ${{ github.repository_owner }}.files* || true
          [ ! -f out/build-state.json ] && echo '{}' > out/build-state.json
          cp out/build-state.json .

      - name: Import GPG key
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import
          echo RELOADAGENT | gpg-connect-agent
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Configure makepkg
        run: |
          KEYID=$(gpg --list-secret-keys --with-colons | awk -F: '/^sec:/ { print $5; exit }')
          echo "GPGKEY=$KEYID" >> ~/.makepkg.conf
          echo "PACKAGER='GitHub Actions Builder <github-actions[bot]@users.noreply.github.com>'" >> ~/.makepkg.conf
          echo "PKGEXT='.pkg.tar.xz'" >> ~/.makepkg.conf
          echo "SRCEXT='.src.tar.gz'" >> ~/.makepkg.conf
          echo "MAKEFLAGS='-j$(nproc)'" >> ~/.makepkg.conf

      - name: Build only changed packages (environment = default)
        shell: bash
        env:
          BUILD_ENVIRONMENT: "default"
        run: |
          bash arch-repo/.github/workflows/scripts/build-packages.sh "$BUILD_ENVIRONMENT"

      - name: Build only changed packages (environment = signed-efi)
        shell: bash
        env:
          BUILD_ENVIRONMENT: "signed-efi"
          SB_KEY_ASCII: ${{ secrets.SECURE_BOOT_KEY }}
          SB_CERT_ASCII: ${{ secrets.SECURE_BOOT_CERTIFICATE }}
        run: |
          echo "$SB_KEY_ASCII" > sb.key
          echo "$SB_CERT_ASCII" > sb.crt
          export SB_SIGN_KEY=$(pwd)/sb.key
          export SB_SIGN_CERT=$(pwd)/sb.crt
          bash arch-repo/.github/workflows/scripts/build-packages.sh "$BUILD_ENVIRONMENT"
          rm -rf {$SB_SIGN_KEY,$SB_SIGN_CERT}

      - name: Add packages to release
        shell: bash
        run: |
          mkdir -p gh-pages
          cd out
          KEYID=$(gpg --list-secret-keys --with-colons | awk -F: '/^sec:/ { print $5; exit }')
          if ls *.pkg.tar.xz >/dev/null 2>&1; then
            repo-add -s -k $KEYID ${{ github.repository_owner }}.db.tar.gz *.pkg.tar.xz
            rm -rf *.html
            alpm-html --output ../gh-pages/ --name ${{ github.repository_owner }} \
              --description "Arch Linux Repository" --key-id $KEYID \
              --url https://github.com/${{ github.repository_owner }}/arch-repo/releases/download/$arch
            echo "NEW_PKGS=TRUE" >> "$GITHUB_ENV"
          fi

      - name: Save new build-state
        if: env.NEW_PKGS == 'TRUE'
        run: cp build-state.json out/build-state.json

      - name: Remove old versions of built packages
        if: env.NEW_PKGS == 'TRUE'
        shell: bash
        run: |
          shopt -s nullglob
          TO_REMOVE=()
          for file in $(basename -a out/*.pkg.tar.xz); do
              BASE=$(echo $file | sed 's/\([a-z-]*\)-[0-9].*/\1/')
              TO_REMOVE+="$(gh release view aarch64 --repo ${{ github.repository }} --json assets -q '.assets[].name | select(endswith(".pkg.tar.xz"))' 2>/dev/null | grep -E "${BASE}-[0-9].*" || true)"
          done
          for file in $TO_REMOVE; do
              echo "Deleting $file..."
              gh release delete-asset aarch64 --repo ${{ github.repository }} -y $file || true
              gh release delete-asset aarch64 --repo ${{ github.repository }} -y $file.sig || true
          done

      - name: Upload to releases
        if: env.NEW_PKGS == 'TRUE'
        shell: bash
        run: |
          shopt -s nullglob
          echo "Uploading package files..."
          for file in $(basename -a out/*.pkg.tar.xz{,.sig}); do
          	gh release upload aarch64 --repo ${{ github.repository }} --clobber out/"$file"
          done
          echo "Uploading repo files..."
          for file in $(basename -a out/${{ github.repository_owner }}.{db*,files*}); do
            gh release upload aarch64 --repo ${{ github.repository }} --clobber out/"$file"
          done
          echo "Uploading build status file..."
          gh release upload aarch64 --repo ${{ github.repository }} --clobber out/build-state.json

      - name: Push to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main' && env.NEW_PKGS == 'TRUE'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./gh-pages
          force_orphan: true
