name: Build & Sync Packages

on:
  push:
    branches:
      - main
    paths:
      - 'packages.json'
      - '.github/workflows/build-packages.yml'
      - '.github/workflows/scripts/**'

  schedule:
    - cron: '0 0 * * 1'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    
    permissions:
      packages: read
      contents: write

    container: 
      image: ghcr.io/${{ github.repository_owner }}/archlinux-builder:latest

    steps:

      - name: Update system
        run: sudo pacman -Syu --noconfirm
  
      - name: Setup git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages
      
      - name: Checkout arch-repo
        uses: actions/checkout@v4
        with:
          path: arch-repo
          fetch-depth: 0

      - name: Load config
        run: |
          cp arch-repo/packages.json .
          [ ! -f gh-pages/build-state.json ] && echo '{}' > gh-pages/build-state.json
          cp gh-pages/build-state.json .

      - name: Import GPG key
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import
          echo RELOADAGENT | gpg-connect-agent
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Configure makepkg
        run: |
          KEYID=$(gpg --list-secret-keys --with-colons | awk -F: '/^sec:/ { print $5; exit }')
          echo "GPGKEY=$KEYID" >> ~/.makepkg.conf
          echo "PACKAGER='GitHub Actions Builder <github-actions[bot]@users.noreply.github.com>'" >> ~/.makepkg.conf
          echo "PKGEXT='.pkg.tar.xz'" >> ~/.makepkg.conf
          echo "SRCEXT='.src.tar.gz'" >> ~/.makepkg.conf
          echo "MAKEFLAGS='-j$(nproc)'" >> ~/.makepkg.conf

      - name: Build only changed packages (environment = default)
        shell: bash
        env:
          BUILD_ENVIRONMENT: "default"
        run: |
          bash arch-repo/.github/workflows/scripts/build-packages.sh "$BUILD_ENVIRONMENT"

      - name: Build only changed packages (environment = signed-efi)
        shell: bash
        env:
          BUILD_ENVIRONMENT: "signed-efi"
          SB_KEY_ASCII: ${{ secrets.SECURE_BOOT_KEY }}
          SB_CERT_ASCII: ${{ secrets.SECURE_BOOT_CERTIFICATE }}
        run: |
          echo "$SB_KEY_ASCII" > sb.key
          echo "$SB_CERT_ASCII" > sb.crt
          export SB_SIGN_KEY=$(pwd)/sb.key
          export SB_SIGN_CERT=$(pwd)/sb.crt
          bash arch-repo/.github/workflows/scripts/build-packages.sh "$BUILD_ENVIRONMENT"
          rm -rf {$SB_SIGN_KEY,$SB_SIGN_CERT}

      - name: Remove old versions of built packages
        run: |
          for file in $(basename -a out/*.pkg.tar.xz); do
          	BASE=$(echo $file | sed 's/\([a-z-]*\)-[0-9].*/\1/')
          	ls gh-pages/*.pkg.tar.xz{,.sig} | grep -E ".*/${BASE}-[0-9].*" | xargs rm -v -f "{}"
          done

      - name: Add packages to gh-pages
        run: |
          cp out/*.pkg.tar.xz out/*.sig gh-pages/ 2>/dev/null || true
          cd gh-pages
          KEYID=$(gpg --list-secret-keys --with-colons | awk -F: '/^sec:/ { print $5; exit }')
          if ls *.pkg.tar.xz >/dev/null 2>&1; then
            repo-add -s -k $KEYID ${{ github.repository_owner }}.db.tar.gz *.pkg.tar.xz
            rm -rf *.html
            alpm-html --output ./ --name ${{ github.repository_owner }} \
              --description "Arch Linux Repository" --key-id $KEYID \
              --url https://${{ github.repository_owner }}github.io/arch-repo
          fi

      - name: Save new build-state
        run: cp build-state.json gh-pages/build-state.json

      - name: Push to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./gh-pages
          force_orphan: true
